charbot/tictactoe.py
=> Make it so hard is defaulted to false (by inverting it into easy)

README.md
Remove codefactor badge from README.md because i've stopped using their service
=> [no ci] Update README.md

charbot/programs/__init__.py, charbot/programs/minesweeper.py, i18n/en-US/programs.ftl
=> Switch minesweeper to out of beta

.github/workflows/ci.yml, schema.sql, tests/charbot/conftest.py, tests/charbot/test_sudoku.py
=> Setup a proper testing system for pools

charbot/levels.py
=> Bugfix on level.py

charbot/translator.py, tests/charbot/test_translator.py
Fix issue with passing context with data into translator translate function.
Add test file for translator.
=> Fix minesweeper rep earned message

.github/workflows/ci.yml, charbot_rust/pyproject.toml, codecov.yml, pyproject.toml
=> Audit Continuous Integration system

charbot/betas/views/banner.py, charbot/bot.py, charbot/pools.py, charbot/programs/minesweeper.py, charbot/programs/shrugman/modal.py, charbot/programs/shrugman/view.py, charbot/programs/sudoku/block.py, charbot/programs/sudoku/cell.py, charbot/programs/sudoku/column.py, charbot/programs/sudoku/puzzle.py, charbot/programs/sudoku/row.py, charbot/programs/sudoku/view.py, charbot/programs/tictactoe.py, tests/charbot/test_shrugman.py, tests/charbot/test_sudoku.py, tests/charbot/test_tictactoe.py
- 
A lot of program classes cannot be assigned arbitrary attributes at runtime anymore
Closes: #238
=> Add __slots__ to program classes

charbot/bot.py, charbot/giveaway.py, pyproject.toml, tests/charbot/test_giveaway.py
- Fix one bug in giveaway code
- Add unittests so that #248 can be unblocked.
=> Add tests for giveaway code

charbot/giveaway/__init__.py, charbot/giveaway/cog.py, charbot/giveaway/modal.py, charbot/giveaway/view.py, tests/charbot/test_giveaway.py
refactoring giveaway.py into a package.
Closes: 237
- Python version not mentioned. @Bluesy1: pleas share python version, getting syntax errors.
- Testcases pending, waiting for python version
=> Refractor `giveaway.py` into a package based cog

charbot_rust/src/fluent/translator.rs, charbot_rust/src/minesweeper.rs, charbot_rust/src/points.rs, charbot_rust/src/tictactoe.rs, charbot_rust/src/tictactoe/board.rs
=> Switch to action-rs/grcov

charbot_rust/src/fluent.rs, charbot_rust/src/fluent/bundle.rs
=> Fix Sentry.io issue Charbot 3B

charbot/betas/banner.py, charbot/betas/cog.py, charbot/bot.py, charbot/card.py, charbot/events.py, charbot/gcal.py, charbot/giveaway/view.py, charbot/programs/shrugman/modal.py, charbot/programs/sudoku/view.py, tests/charbot/test_giveaway.py
- Fix broken tests caused by 3a07e14c1083ac94bc5965e954201018fa25f1bb
- Fix incorrectly reported missing branches
Closes: NaN
=> Fix broken tests and mark purposely missed branches to not count

.codeclimate.yml, .github/workflows/ci.yml, README.md, codecov.yml
- Delegates codecov status checks to informational for now
- In the future, codecov may be disabled for rust too, and manuall checking of coverage/switching to another provider may happen
- Stops uploading python to codecov
- Uploads python to codeclimate
Codecov has had many issues for me in python, including missing a lot of files, and thus misrepoting coverage, and I need to have proper coverage reported.
Closes: NaN
=> Switch to codeclimate from codecov for python

charbot/admin.py, charbot/events.py, tests/charbot/test_events.py
- Removes sensitive scan code
Closes: NaN
=> Remove sensitive scan

charbot/levels.py
Made it 15 minutes instead of an hour.
=> Changed /rank cooldown from 3600 to 900 seconds

charbot/programs/sudoku/puzzle.py
- Fix sudoku command on mobile due to change in how discord renders on mobile
Closes: NaN
=> Bug: Fix issues raised about sudoku command on mobile

charbot/bot.py
=> Remove unnecessary `#type: ignore`

charbot/query.py
- Changed the is_animated attribute to getattr
Closes: NaN
=> #322 Issue Update: AttributeError is_animated

charbot/__init__.py, charbot/events.py
- Change links allowance in forum channel for games 
Closes: NaN
=> Allow starter messages in the games forum channel to have links

pyproject.toml
Update pinned discord.py version to support pomelo - Works towards #375
=> Bump discord.py to support pomelo

charbot/levels.py, schema.sql
=> New levels system (2025)
